import { jsPDF } from 'jspdf';
import type { AuditReport } from './report';
import { formatReportDate, reportFilenameSlug } from './report';

// Built programmatically (not via html2canvas) so the output is crisp vector text
// with real page breaks — and so it never trips over the app's oklch() CSS colors,
// which html2canvas cannot parse.

const MARGIN = 48;
const LINE = 13;

const INK: [number, number, number] = [26, 26, 26];
const BODY: [number, number, number] = [70, 70, 70];
const MUTED: [number, number, number] = [120, 120, 120];
const PASS: [number, number, number] = [22, 130, 80];
const FAIL: [number, number, number] = [190, 50, 50];

/** Render a page's audit report to a jsPDF document. */
export function buildAuditReportPdf(report: AuditReport): jsPDF {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const contentW = pageW - MARGIN * 2;
  let y = MARGIN;

  const ensure = (needed: number) => {
    if (y + needed > pageH - MARGIN) {
      doc.addPage();
      y = MARGIN;
    }
  };

  const paragraph = (
    text: string,
    opts: { size: number; color: [number, number, number]; bold?: boolean; indent?: number },
  ) => {
    doc.setFont('helvetica', opts.bold ? 'bold' : 'normal');
    doc.setFontSize(opts.size);
    doc.setTextColor(...opts.color);
    const x = MARGIN + (opts.indent ?? 0);
    const wrapped = doc.splitTextToSize(text, contentW - (opts.indent ?? 0));
    const lh = opts.size + 3;
    ensure(wrapped.length * lh);
    doc.text(wrapped, x, y);
    y += wrapped.length * lh;
  };

  // Title
  paragraph('AI Readability Report', { size: 20, color: INK, bold: true });
  y += 6;

  // Page identity
  paragraph(report.title, { size: 12, color: INK });
  paragraph(report.pageUrl, { size: 9, color: MUTED });
  y += 8;

  // Score summary
  paragraph(
    `Score: ${report.score}/100  ·  ${report.tierLabel}  ·  ${report.passingCount}/${report.totalCount} checks passing`,
    { size: 11, color: INK, bold: true },
  );
  paragraph(`Audited ${formatReportDate(report.fetchedAt)}`, { size: 9, color: MUTED });
  y += 14;

  // Category breakdown
  paragraph('Category breakdown', { size: 12, color: INK, bold: true });
  y += 4;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  for (const c of report.categories) {
    ensure(LINE + 2);
    doc.setTextColor(...BODY);
    doc.text(c.label, MARGIN, y);
    doc.setTextColor(...MUTED);
    doc.text(`${c.score}/100`, pageW - MARGIN, y, { align: 'right' });
    y += LINE + 2;
  }
  y += 12;

  // Checks
  paragraph('Checks', { size: 12, color: INK, bold: true });
  y += 4;
  for (const c of report.checks) {
    ensure(LINE + 4);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10.5);
    doc.setTextColor(...(c.passed ? PASS : FAIL));
    doc.text(c.passed ? 'PASS' : 'FAIL', MARGIN, y);
    doc.setTextColor(...INK);
    doc.text(c.label, MARGIN + 36, y);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(...MUTED);
    doc.text(`${c.score}/100 · weight ${c.weight}`, pageW - MARGIN, y, { align: 'right' });
    y += LINE + 1;

    if (c.evidence.length > 0) {
      paragraph(`Found: ${c.evidence.join(' ')}`, { size: 9.5, color: BODY, indent: 36 });
    }
    if (c.recommendation) {
      paragraph(`Fix: ${c.recommendation}`, { size: 9.5, color: INK, indent: 36 });
    }
    y += 8;
  }

  // Footer on every page
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text('Generated by make-a-llms.txt', MARGIN, pageH - 24);
    doc.text(`Page ${i} of ${pages}`, pageW - MARGIN, pageH - 24, { align: 'right' });
  }

  return doc;
}

export function auditReportPdfFilename(report: AuditReport): string {
  return `ai-readability-${reportFilenameSlug(report.pageUrl)}.pdf`;
}

/** Build the report PDF and trigger a browser download. */
export function downloadAuditReportPdf(report: AuditReport): void {
  buildAuditReportPdf(report).save(auditReportPdfFilename(report));
}
