'use client';

import { useMemo, useState } from 'react';
import { Button } from '@/components/ui/button';
import {
  KNOWN_AI_BOTS,
  type AuditResults,
  type KnownAiBot,
} from '@/lib/known-ai-bots';
import { cn } from '@/lib/utils';

type ToggleState = 'allow' | 'block' | 'default';

function seedToggles(initial: AuditResults): Record<KnownAiBot, ToggleState> {
  return Object.fromEntries(
    KNOWN_AI_BOTS.map((bot) => {
      const status = initial[bot]?.status;
      const t: ToggleState =
        status === 'allowed' ? 'allow' : status === 'blocked' ? 'block' : 'default';
      return [bot, t];
    }),
  ) as Record<KnownAiBot, ToggleState>;
}

function buildSnippet(
  toggles: Record<KnownAiBot, ToggleState>,
  dateIso: string,
): string {
  const allowed = KNOWN_AI_BOTS.filter((b) => toggles[b] === 'allow');
  const blocked = KNOWN_AI_BOTS.filter((b) => toggles[b] === 'block');

  const lines: string[] = [
    `# Generated by AI Ready — ${dateIso}`,
    `# Append to your existing robots.txt.`,
  ];

  if (allowed.length === 0 && blocked.length === 0) {
    lines.push('');
    lines.push('# (No directives — toggle a bot to begin)');
    return lines.join('\n');
  }

  if (allowed.length > 0) {
    lines.push('');
    lines.push('# Allowed AI crawlers');
    for (const b of allowed) lines.push(`User-agent: ${b}`);
    lines.push('Allow: /');
  }

  if (blocked.length > 0) {
    lines.push('');
    lines.push('# Blocked AI crawlers');
    for (const b of blocked) lines.push(`User-agent: ${b}`);
    lines.push('Disallow: /');
  }

  return lines.join('\n');
}

export function RobotsGenerator({ initial }: { initial: AuditResults }) {
  const [toggles, setToggles] = useState(() => seedToggles(initial));

  const snippet = useMemo(
    () => buildSnippet(toggles, new Date().toISOString().slice(0, 10)),
    [toggles],
  );
  const empty = useMemo(
    () => KNOWN_AI_BOTS.every((b) => toggles[b] === 'default'),
    [toggles],
  );

  function set(bot: KnownAiBot, next: 'allow' | 'block'): void {
    setToggles((prev) => ({
      ...prev,
      [bot]: prev[bot] === next ? 'default' : next,
    }));
  }

  return (
    <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
      <div className="rounded-xl border border-hairline bg-surface-card">
        <table className="w-full">
          <tbody>
            {KNOWN_AI_BOTS.map((bot) => (
              <tr
                key={bot}
                className="border-b border-hairline-soft last:border-0"
              >
                <td className="px-4 py-3 font-mono text-[13px] text-ink">
                  {bot}
                </td>
                <td className="px-4 py-3">
                  <div className="flex gap-2">
                    <button
                      type="button"
                      aria-pressed={toggles[bot] === 'allow'}
                      onClick={() => set(bot, 'allow')}
                      className={cn(
                        'rounded-full border px-3 py-1 text-xs transition-colors',
                        toggles[bot] === 'allow'
                          ? 'border-semantic-success bg-semantic-success/20 text-[#155e44]'
                          : 'border-hairline-strong text-body hover:text-ink',
                      )}
                    >
                      Allow
                    </button>
                    <button
                      type="button"
                      aria-pressed={toggles[bot] === 'block'}
                      onClick={() => set(bot, 'block')}
                      className={cn(
                        'rounded-full border px-3 py-1 text-xs transition-colors',
                        toggles[bot] === 'block'
                          ? 'border-destructive bg-destructive/15 text-destructive'
                          : 'border-hairline-strong text-body hover:text-ink',
                      )}
                    >
                      Block
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        <div className="border-t border-hairline px-4 py-3">
          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={() => setToggles(seedToggles(initial))}
          >
            Reset to current state
          </Button>
        </div>
      </div>

      <div className="flex flex-col rounded-xl border border-hairline bg-canvas-soft">
        <pre
          data-testid="snippet"
          className="flex-grow overflow-x-auto p-4 font-mono text-[12px] leading-relaxed text-ink"
        >
          {snippet}
        </pre>
        <div className="border-t border-hairline px-4 py-3">
          <Button
            type="button"
            size="sm"
            disabled={empty}
            onClick={() => navigator.clipboard.writeText(snippet)}
          >
            Copy snippet
          </Button>
        </div>
      </div>
    </div>
  );
}
