'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
import {
  KNOWN_AI_BOTS,
  type AuditResults,
  type KnownAiBot,
} from '@/lib/known-ai-bots';
import { wildcardPosture, wildcardBlocksRoot } from '@/lib/robots-wildcard';
import { cn } from '@/lib/utils';

type ToggleState = 'allow' | 'block' | 'default';
type WarningKind = 'no-robots' | 'wildcard-block' | null;

function stripWildcardGroup(content: string): string {
  const lines = content.split(/\r?\n/);
  const out: string[] = [];
  let skipping = false;

  for (const rawLine of lines) {
    const stripped = rawLine.replace(/#.*$/, '').trim();
    const colon = stripped.indexOf(':');

    // Comments or blank lines: drop while inside a skipped group, otherwise preserve.
    if (colon <= 0) {
      if (skipping) continue;
      out.push(rawLine);
      continue;
    }

    const directive = stripped.slice(0, colon).trim().toLowerCase();
    const value = stripped.slice(colon + 1).trim();

    if (directive === 'user-agent') {
      skipping = value === '*';
      if (skipping) continue;
      out.push(rawLine);
      continue;
    }

    // Top-level directives survive even inside a skipped group.
    if (directive === 'sitemap' || directive === 'host') {
      out.push(rawLine);
      continue;
    }

    // Group-scoped directives (Allow, Disallow, Crawl-delay, Clean-param, etc.)
    if (skipping) continue;
    out.push(rawLine);
  }

  while (out.length && out[out.length - 1].trim() === '') out.pop();
  return out.join('\n');
}

function seedToggles(initial: AuditResults): Record<KnownAiBot, ToggleState> {
  return Object.fromEntries(
    KNOWN_AI_BOTS.map((bot) => {
      const status = initial[bot]?.status;
      const t: ToggleState =
        status === 'allowed' ? 'allow' : status === 'blocked' ? 'block' : 'default';
      return [bot, t];
    }),
  ) as Record<KnownAiBot, ToggleState>;
}

function buildSnippet(
  toggles: Record<KnownAiBot, ToggleState>,
  dateIso: string,
  existingWildcard: 'allow' | 'disallow' | 'unset',
  allowAll: boolean,
): string {
  const addWildcardRule = allowAll && existingWildcard !== 'allow';
  // The effective wildcard considers what we're about to emit.
  const effectiveWildcard: 'allow' | 'disallow' | 'unset' = addWildcardRule
    ? 'allow'
    : existingWildcard;

  const allowed = KNOWN_AI_BOTS.filter((b) => toggles[b] === 'allow');
  const blocked = KNOWN_AI_BOTS.filter((b) => toggles[b] === 'block');

  const lines: string[] = [`# Generated by AI Ready — ${dateIso}`];

  if (addWildcardRule) {
    lines.push('');
    lines.push('# Allow all crawlers (including non-AI bots)');
    lines.push('User-agent: *');
    lines.push('Allow: /');
  }

  if (allowed.length > 0) {
    lines.push('');
    if (effectiveWildcard === 'allow') {
      lines.push('# Already allowed by User-agent: * (no explicit Allow needed):');
      lines.push(`#   ${allowed.join(', ')}`);
    } else {
      lines.push('# Allowed AI crawlers');
      for (const b of allowed) lines.push(`User-agent: ${b}`);
      lines.push('Allow: /');
    }
  }

  if (blocked.length > 0) {
    lines.push('');
    if (effectiveWildcard === 'disallow') {
      lines.push('# Already blocked by User-agent: * (no explicit Disallow needed):');
      lines.push(`#   ${blocked.join(', ')}`);
    } else {
      lines.push('# Blocked AI crawlers');
      for (const b of blocked) lines.push(`User-agent: ${b}`);
      lines.push('Disallow: /');
    }
  }

  return lines.join('\n');
}

export function RobotsGenerator({
  siteId,
  initial,
  robotsContent,
}: {
  siteId: string;
  initial: AuditResults;
  robotsContent: string | null;
}) {
  const qc = useQueryClient();
  const draftKey = useMemo(
    () => ['sites', siteId, 'generator-draft'] as const,
    [siteId],
  );

  const draft = useQuery({
    queryKey: draftKey,
    queryFn: async () => {
      const res = await fetch(`/api/sites/${siteId}/generator-draft`);
      if (res.status === 404) return null;
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      return (await res.json()) as {
        draft: { toggles: string; allowAll: boolean };
      };
    },
  });

  const seeded = useMemo(() => seedToggles(initial), [initial]);
  const [toggles, setToggles] = useState<Record<KnownAiBot, ToggleState>>(seeded);
  const [allowAllDraft, setAllowAllDraft] = useState(false);
  const hydrated = useRef(false);

  // Hydrate from the saved draft once it arrives; otherwise leave at audit seed.
  useEffect(() => {
    if (hydrated.current) return;
    if (draft.isLoading) return;
    hydrated.current = true;
    if (!draft.data) return;
    try {
      const parsed = JSON.parse(draft.data.draft.toggles) as Record<string, ToggleState>;
      // eslint-disable-next-line react-hooks/set-state-in-effect -- one-time hydration from server-fetched draft after mount; not a cascading-render risk.
      setToggles((prev) => {
        const next = { ...prev };
        for (const bot of KNOWN_AI_BOTS) {
          const v = parsed[bot];
          if (v === 'allow' || v === 'block' || v === 'default') next[bot] = v;
        }
        return next;
      });
      setAllowAllDraft(Boolean(draft.data.draft.allowAll));
    } catch {
      // ignore corrupt draft
    }
  }, [draft.data, draft.isLoading]);

  const save = useMutation({
    mutationFn: async (next: {
      toggles: Record<KnownAiBot, ToggleState>;
      allowAll: boolean;
    }) => {
      const res = await fetch(`/api/sites/${siteId}/generator-draft`, {
        method: 'PUT',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify(next),
      });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: draftKey }),
  });

  const saveTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  // Hold the latest mutate fn in a ref so scheduleSave doesn't capture stale closures.
  const saveRef = useRef(save);
  useEffect(() => {
    saveRef.current = save;
  });

  useEffect(() => {
    return () => {
      if (saveTimer.current) clearTimeout(saveTimer.current);
    };
  }, []);

  function scheduleSave(next: {
    toggles: Record<KnownAiBot, ToggleState>;
    allowAll: boolean;
  }): void {
    if (saveTimer.current) clearTimeout(saveTimer.current);
    saveTimer.current = setTimeout(() => {
      saveRef.current.mutate(next);
    }, 400);
  }

  const wildcard = useMemo(
    () => wildcardPosture(robotsContent),
    [robotsContent],
  );

  const existingWildcard = wildcard;

  const allowAllDisplay: boolean =
    wildcard === 'allow' ? true : allowAllDraft;

  const effectiveWildcard: 'allow' | 'disallow' | 'unset' =
    allowAllDraft || existingWildcard === 'allow' ? 'allow' : existingWildcard;

  type Visual = 'allow' | 'block' | 'default';
  function visualState(bot: KnownAiBot): Visual {
    const t = toggles[bot];
    if (t !== 'default') return t;
    if (effectiveWildcard === 'allow') return 'allow';
    return 'default';
  }

  function set(bot: KnownAiBot, nextValue: 'allow' | 'block'): void {
    setToggles((prev) => {
      const updated = {
        ...prev,
        [bot]: prev[bot] === nextValue ? 'default' : nextValue,
      } as Record<KnownAiBot, ToggleState>;
      scheduleSave({ toggles: updated, allowAll: allowAllDraft });
      return updated;
    });
  }

  function enableAllowAll(): void {
    setAllowAllDraft(true);
    scheduleSave({ toggles, allowAll: true });
  }

  function reset(): void {
    const fresh = seedToggles(initial);
    setToggles(fresh);
    setAllowAllDraft(false);
    scheduleSave({ toggles: fresh, allowAll: false });
  }

  const generatedBlock = useMemo(
    () =>
      buildSnippet(
        toggles,
        new Date().toISOString().slice(0, 10),
        wildcard,
        allowAllDisplay,
      ),
    [toggles, wildcard, allowAllDisplay],
  );

  const snippet = useMemo(() => {
    if (!robotsContent) return generatedBlock;
    const prepend = allowAllDraft
      ? stripWildcardGroup(robotsContent)
      : robotsContent.replace(/\s+$/, '');
    if (!prepend.trim()) return generatedBlock;
    return `${prepend}\n\n# === AI Ready directives ===\n${generatedBlock}`;
  }, [robotsContent, generatedBlock, allowAllDraft]);

  const empty = useMemo(
    () => KNOWN_AI_BOTS.every((b) => toggles[b] === 'default'),
    [toggles],
  );

  function download(): void {
    const blob = new Blob([snippet], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'robots.txt';
    a.click();
    URL.revokeObjectURL(url);
  }

  const warning: WarningKind = useMemo(() => {
    if (robotsContent === null) return 'no-robots';
    if (wildcardBlocksRoot(robotsContent)) return 'wildcard-block';
    return null;
  }, [robotsContent]);

  const [dismissed, setDismissed] = useState(false);

  return (
    <div className="space-y-6">
      {warning && !dismissed && (
        <div
          role="alert"
          className="flex items-start justify-between gap-3 rounded-xl border border-timeline-thinking/60 bg-timeline-thinking/15 p-4"
        >
          <div className="space-y-2">
            <div className="caption-uppercase text-[#7a4229]">Heads up</div>
            {warning === 'no-robots' ? (
              <p className="text-sm text-ink">
                This site has no robots.txt. The directives below will be your starting point.
              </p>
            ) : (
              <>
                <p className="text-sm text-ink">
                  No bots can access your site. Your robots.txt blocks every crawler
                  via <code className="font-mono">User-agent: *</code> +{' '}
                  <code className="font-mono">Disallow: /</code>.
                </p>
                {!allowAllDraft && (
                  <Button type="button" size="sm" onClick={enableAllowAll}>
                    Switch to Allow: /
                  </Button>
                )}
              </>
            )}
          </div>
          <button
            type="button"
            onClick={() => setDismissed(true)}
            className="caption-uppercase text-muted-strong hover:text-ink"
            aria-label="Dismiss warning"
          >
            Dismiss
          </button>
        </div>
      )}

      <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
      <div className="rounded-xl border border-hairline bg-surface-card">
        <table className="w-full">
          <tbody>
            {KNOWN_AI_BOTS.map((bot) => {
              const visual = visualState(bot);
              return (
                <tr
                  key={bot}
                  className="border-b border-hairline-soft last:border-0"
                >
                  <td className="px-4 py-3 font-mono text-[13px] text-ink">
                    {bot}
                  </td>
                  <td className="px-4 py-3">
                    <div className="flex justify-end gap-2">
                      <button
                        type="button"
                        aria-pressed={visual === 'allow'}
                        onClick={() => set(bot, 'allow')}
                        className={cn(
                          'rounded-full border px-3 py-1 text-xs transition-colors',
                          visual === 'allow'
                            ? 'border-semantic-success bg-semantic-success/20 text-[#155e44]'
                            : 'border-hairline-strong text-body hover:text-ink',
                        )}
                      >
                        Allow
                      </button>
                      <button
                        type="button"
                        aria-pressed={visual === 'block'}
                        onClick={() => set(bot, 'block')}
                        className={cn(
                          'rounded-full border px-3 py-1 text-xs transition-colors',
                          visual === 'block'
                            ? 'border-destructive bg-destructive/15 text-destructive'
                            : 'border-hairline-strong text-body hover:text-ink',
                        )}
                      >
                        Block
                      </button>
                    </div>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
        {existingWildcard === 'unset' && !allowAllDraft && (
          <div className="border-t border-hairline px-4 py-3">
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={enableAllowAll}
            >
              Allow all crawlers
            </Button>
            <p className="mt-1 text-xs text-muted-strong">
              Add a wildcard rule that lets every bot crawl your site.
            </p>
          </div>
        )}
        <div className="border-t border-hairline px-4 py-3">
          <Button type="button" variant="outline" size="sm" onClick={reset}>
            Reset to current state
          </Button>
        </div>
      </div>

      <div className="flex flex-col rounded-xl border border-hairline bg-canvas-soft">
        <pre
          data-testid="snippet"
          className="flex-grow overflow-x-auto p-4 font-mono text-[12px] leading-relaxed text-ink"
        >
          {snippet}
        </pre>
        <div className="flex gap-2 border-t border-hairline px-4 py-3">
          <Button
            type="button"
            size="sm"
            disabled={empty}
            onClick={() => navigator.clipboard.writeText(snippet)}
          >
            Copy snippet
          </Button>
          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={download}
          >
            Download robots.txt
          </Button>
        </div>
      </div>
      </div>
    </div>
  );
}
