'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
import {
  KNOWN_AI_BOTS,
  type AuditResults,
  type KnownAiBot,
} from '@/lib/known-ai-bots';
import { parseRobotsTxt } from '@/lib/robots-parser';
import { cn } from '@/lib/utils';

type ToggleState = 'allow' | 'block' | 'default';
type WarningKind = 'no-robots' | 'wildcard-block' | null;

function wildcardPosture(content: string | null): 'allow' | 'disallow' | 'unset' {
  if (content === null) return 'unset';
  const groups = parseRobotsTxt(content);
  for (const g of groups) {
    if (!g.userAgents.some((ua) => ua.trim() === '*')) continue;
    // Determine if root "/" is allowed for this wildcard group.
    // Walk rules; for each rule whose path matches root, track the longest
    // match. On length tie, allow wins (mirrors RFC 9309 semantics).
    let best: { type: 'allow' | 'disallow'; length: number } | null = null;
    for (const r of g.rules) {
      if (r.path !== '' && r.path !== '/' && r.path !== '/*') continue;
      const len = r.path.length;
      if (
        !best ||
        len > best.length ||
        (len === best.length && r.type === 'allow')
      ) {
        best = { type: r.type, length: len };
      }
    }
    if (!best) return 'allow';
    return best.type === 'allow' ? 'allow' : 'disallow';
  }
  return 'unset';
}

function wildcardBlocksRoot(content: string): boolean {
  return wildcardPosture(content) === 'disallow';
}

function seedToggles(initial: AuditResults): Record<KnownAiBot, ToggleState> {
  return Object.fromEntries(
    KNOWN_AI_BOTS.map((bot) => {
      const status = initial[bot]?.status;
      const t: ToggleState =
        status === 'allowed' ? 'allow' : status === 'blocked' ? 'block' : 'default';
      return [bot, t];
    }),
  ) as Record<KnownAiBot, ToggleState>;
}

function buildSnippet(
  toggles: Record<KnownAiBot, ToggleState>,
  dateIso: string,
  wildcard: 'allow' | 'disallow' | 'unset',
): string {
  const allowed = KNOWN_AI_BOTS.filter((b) => toggles[b] === 'allow');
  const blocked = KNOWN_AI_BOTS.filter((b) => toggles[b] === 'block');

  const emitAllowed = allowed.length > 0 && wildcard !== 'allow';
  const emitBlocked = blocked.length > 0 && wildcard !== 'disallow';

  const lines: string[] = [
    `# Generated by AI Ready — ${dateIso}`,
    `# Append to your existing robots.txt.`,
  ];

  if (!emitAllowed && !emitBlocked) {
    lines.push('');
    lines.push('# (No directives — toggle a bot to begin)');
    return lines.join('\n');
  }

  if (emitAllowed) {
    lines.push('');
    lines.push('# Allowed AI crawlers');
    for (const b of allowed) lines.push(`User-agent: ${b}`);
    lines.push('Allow: /');
  }

  if (emitBlocked) {
    lines.push('');
    lines.push('# Blocked AI crawlers');
    for (const b of blocked) lines.push(`User-agent: ${b}`);
    lines.push('Disallow: /');
  }

  return lines.join('\n');
}

export function RobotsGenerator({
  siteId,
  initial,
  robotsContent,
}: {
  siteId: number;
  initial: AuditResults;
  robotsContent: string | null;
}) {
  const qc = useQueryClient();
  const draftKey = useMemo(
    () => ['sites', siteId, 'generator-draft'] as const,
    [siteId],
  );

  const draft = useQuery({
    queryKey: draftKey,
    queryFn: async () => {
      const res = await fetch(`/api/sites/${siteId}/generator-draft`);
      if (res.status === 404) return null;
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      return (await res.json()) as { draft: { toggles: string } };
    },
  });

  const seeded = useMemo(() => seedToggles(initial), [initial]);
  const [toggles, setToggles] = useState<Record<KnownAiBot, ToggleState>>(seeded);
  const hydrated = useRef(false);

  // Hydrate from the saved draft once it arrives; otherwise leave at audit seed.
  useEffect(() => {
    if (hydrated.current) return;
    if (draft.isLoading) return;
    hydrated.current = true;
    if (!draft.data) return;
    try {
      const parsed = JSON.parse(draft.data.draft.toggles) as Record<string, ToggleState>;
      // eslint-disable-next-line react-hooks/set-state-in-effect -- one-time hydration from server-fetched draft after mount; not a cascading-render risk.
      setToggles((prev) => {
        const next = { ...prev };
        for (const bot of KNOWN_AI_BOTS) {
          const v = parsed[bot];
          if (v === 'allow' || v === 'block' || v === 'default') next[bot] = v;
        }
        return next;
      });
    } catch {
      // ignore corrupt draft
    }
  }, [draft.data, draft.isLoading]);

  const save = useMutation({
    mutationFn: async (next: Record<KnownAiBot, ToggleState>) => {
      const res = await fetch(`/api/sites/${siteId}/generator-draft`, {
        method: 'PUT',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ toggles: next }),
      });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: draftKey }),
  });

  const saveTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  // Hold the latest mutate fn in a ref so scheduleSave doesn't capture stale closures.
  const saveRef = useRef(save);
  useEffect(() => {
    saveRef.current = save;
  });

  useEffect(() => {
    return () => {
      if (saveTimer.current) clearTimeout(saveTimer.current);
    };
  }, []);

  function scheduleSave(next: Record<KnownAiBot, ToggleState>): void {
    if (saveTimer.current) clearTimeout(saveTimer.current);
    saveTimer.current = setTimeout(() => {
      saveRef.current.mutate(next);
    }, 400);
  }

  function set(bot: KnownAiBot, nextValue: 'allow' | 'block'): void {
    setToggles((prev) => {
      const updated = {
        ...prev,
        [bot]: prev[bot] === nextValue ? 'default' : nextValue,
      } as Record<KnownAiBot, ToggleState>;
      scheduleSave(updated);
      return updated;
    });
  }

  function reset(): void {
    const fresh = seedToggles(initial);
    setToggles(fresh);
    scheduleSave(fresh);
  }

  const wildcard = useMemo(
    () => wildcardPosture(robotsContent),
    [robotsContent],
  );

  const generatedBlock = useMemo(
    () => buildSnippet(toggles, new Date().toISOString().slice(0, 10), wildcard),
    [toggles, wildcard],
  );

  const snippet = useMemo(() => {
    if (!robotsContent) return generatedBlock;
    const trimmed = robotsContent.replace(/\s+$/, '');
    return `${trimmed}\n\n# === AI Ready generated additions ===\n${generatedBlock}`;
  }, [robotsContent, generatedBlock]);

  const empty = useMemo(
    () => KNOWN_AI_BOTS.every((b) => toggles[b] === 'default'),
    [toggles],
  );

  function download(): void {
    const blob = new Blob([snippet], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'robots.txt';
    a.click();
    URL.revokeObjectURL(url);
  }

  const warning: WarningKind = useMemo(() => {
    if (robotsContent === null) return 'no-robots';
    if (wildcardBlocksRoot(robotsContent)) return 'wildcard-block';
    return null;
  }, [robotsContent]);

  const [dismissed, setDismissed] = useState(false);

  return (
    <div className="space-y-6">
      {warning && !dismissed && (
        <div
          role="alert"
          className="flex items-start justify-between gap-3 rounded-xl border border-timeline-thinking/60 bg-timeline-thinking/15 p-4"
        >
          <div className="space-y-1">
            <div className="caption-uppercase text-[#7a4229]">Heads up</div>
            <p className="text-sm text-ink">
              {warning === 'no-robots'
                ? `This site has no robots.txt. The directives below will be your starting point.`
                : `Your robots.txt blocks all crawlers via User-agent: * Disallow: /. Even bots set to ALLOW below may skip your site if they don't have an explicit allow rule.`}
            </p>
          </div>
          <button
            type="button"
            onClick={() => setDismissed(true)}
            className="caption-uppercase text-muted-strong hover:text-ink"
            aria-label="Dismiss warning"
          >
            Dismiss
          </button>
        </div>
      )}

      <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
      <div className="rounded-xl border border-hairline bg-surface-card">
        <table className="w-full">
          <tbody>
            {KNOWN_AI_BOTS.map((bot) => (
              <tr
                key={bot}
                className="border-b border-hairline-soft last:border-0"
              >
                <td className="px-4 py-3 font-mono text-[13px] text-ink">
                  {bot}
                </td>
                <td className="px-4 py-3">
                  <div className="flex gap-2">
                    <button
                      type="button"
                      aria-pressed={toggles[bot] === 'allow'}
                      onClick={() => set(bot, 'allow')}
                      className={cn(
                        'rounded-full border px-3 py-1 text-xs transition-colors',
                        toggles[bot] === 'allow'
                          ? 'border-semantic-success bg-semantic-success/20 text-[#155e44]'
                          : 'border-hairline-strong text-body hover:text-ink',
                      )}
                    >
                      Allow
                    </button>
                    <button
                      type="button"
                      aria-pressed={toggles[bot] === 'block'}
                      onClick={() => set(bot, 'block')}
                      className={cn(
                        'rounded-full border px-3 py-1 text-xs transition-colors',
                        toggles[bot] === 'block'
                          ? 'border-destructive bg-destructive/15 text-destructive'
                          : 'border-hairline-strong text-body hover:text-ink',
                      )}
                    >
                      Block
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        <div className="border-t border-hairline px-4 py-3">
          <Button type="button" variant="outline" size="sm" onClick={reset}>
            Reset to current state
          </Button>
        </div>
      </div>

      <div className="flex flex-col rounded-xl border border-hairline bg-canvas-soft">
        <pre
          data-testid="snippet"
          className="flex-grow overflow-x-auto p-4 font-mono text-[12px] leading-relaxed text-ink"
        >
          {snippet}
        </pre>
        <div className="flex gap-2 border-t border-hairline px-4 py-3">
          <Button
            type="button"
            size="sm"
            disabled={empty}
            onClick={() => navigator.clipboard.writeText(snippet)}
          >
            Copy snippet
          </Button>
          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={download}
          >
            Download robots.txt
          </Button>
        </div>
      </div>
      </div>
    </div>
  );
}
